# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for pip (poetry)
  - package-ecosystem: "pip"
    # Look for `pyproject.toml` and `lock` files in the `root` directory
    directory: "/"
    # Check the pip registry for updates every week
    schedule:
      interval: "weekly"
